std = "roblox"

[lints]
empty_if = "warn"
incorrect_standard_library_use = "warn"
must_use = "warn"
shadowing = "warn"
suspicious_reverse_usage = "warn"
unscoped_variables = "warn"
unused_variable = "warn"
